---
name: List golang code

on:
  push:
    branches: ["master"]
    paths:
      - '**.go'
  pull_request:
    branches: ["master"]
    paths:
      - '**.go'

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      
      - name: Lint golang code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56
          args: --timeout 3m --config .golangci.yml
